import type { CSSProperties } from "react";

/** Co-located styles for SortableSkillRow. */
export const s = {
  row: (attached: boolean, dragging: boolean, dnd: CSSProperties): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 11,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.6 : attached ? 1 : 0.7,
    zIndex: dragging ? 1 : undefined,
    position: "relative",
    ...dnd,
  }),
  handle: {
    background: "none",
    border: "none",
    padding: 0,
    color: "var(--text-muted)",
    cursor: "grab",
    display: "inline-flex",
    touchAction: "none",
  } satisfies CSSProperties,
  handlePlaceholder: { width: 14, flexShrink: 0 } satisfies CSSProperties,
  checkbox: (on: boolean): CSSProperties => ({
    width: 16,
    height: 16,
    flexShrink: 0,
    borderRadius: 4,
    border: "1.5px solid " + (on ? "var(--accent)" : "var(--border-strong)"),
    background: on ? "var(--accent)" : "transparent",
    display: "grid",
    placeItems: "center",
    cursor: "pointer",
    padding: 0,
  }),
  checkIcon: { color: "#fff" } satisfies CSSProperties,
  name: {
    fontSize: 12.5,
    fontWeight: 600,
    flex: 1,
    minWidth: 0,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  disabledChip: {
    fontSize: 10.5,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
    padding: "1px 7px",
    borderRadius: 4,
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  typePill: (color: string): CSSProperties => ({
    fontSize: 10.5,
    fontWeight: 600,
    color,
    background: color + "1a",
    padding: "1px 7px",
    borderRadius: 4,
  }),
  enabledToggle: { display: "inline-flex", alignItems: "center", flexShrink: 0 } satisfies CSSProperties,
  moveGroup: { display: "inline-flex", gap: 2 } satisfies CSSProperties,
  moveBtn: (disabled: boolean): CSSProperties => ({
    background: "none",
    border: "none",
    padding: 2,
    color: disabled ? "var(--border-strong)" : "var(--text-muted)",
    cursor: disabled ? "not-allowed" : "pointer",
    display: "inline-flex",
  }),
} as const;
