import type { CSSProperties } from "react";

/** Co-located styles for the context-selection panel. */
export const s = {
  wrap: { display: "flex", flexDirection: "column", gap: 12 } satisfies CSSProperties,
  repoRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  label: { fontSize: 12, color: "var(--text-muted)", fontWeight: 600 } satisfies CSSProperties,
  select: {
    flex: 1,
    minWidth: 0,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    fontSize: 13,
  } satisfies CSSProperties,
  list: {
    maxHeight: 320,
    overflow: "auto",
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    fontSize: 13,
  } satisfies CSSProperties,
  rowLabel: { display: "flex", alignItems: "center", gap: 10, flex: 1, minWidth: 0, cursor: "pointer" } satisfies CSSProperties,
  path: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  meta: { fontSize: 12, color: "var(--text-muted)", whiteSpace: "nowrap" } satisfies CSSProperties,
  missing: {
    fontSize: 11,
    fontWeight: 700,
    padding: "1px 6px",
    borderRadius: 4,
    color: "var(--crit)",
    background: "var(--crit-bg)",
  } satisfies CSSProperties,
  linkBtn: {
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    borderRadius: 5,
    padding: "2px 8px",
    fontSize: 12,
    cursor: "pointer",
  } satisfies CSSProperties,
  totals: { display: "flex", flexDirection: "column", gap: 4, fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,
  muted: { fontSize: 13, color: "var(--text-muted)", padding: 12 } satisfies CSSProperties,
  preview: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: "10px 14px",
    maxHeight: 360,
    overflow: "auto",
    fontSize: 13.5,
    color: "var(--text-primary)",
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
} as const;
