import type { CSSProperties } from "react";

/** Co-located styles for ImportSkillDrawer. */
export const s = {
  notice: {
    display: "flex",
    gap: 10,
    alignItems: "flex-start",
    padding: "12px 14px",
    borderRadius: 8,
    border: "1px solid var(--warn)",
    background: "var(--warn-bg)",
    color: "var(--text-primary)",
    fontSize: 12.5,
    lineHeight: 1.5,
    marginBottom: 16,
  } satisfies CSSProperties,
  noticeIcon: { color: "var(--warn)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  picker: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "14px 16px",
    borderRadius: 9,
    border: "1.5px dashed var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
  } satisfies CSSProperties,
  fileInput: { display: "none" } satisfies CSSProperties,
  status: { fontSize: 12.5, color: "var(--text-muted)", marginTop: 12 } satisfies CSSProperties,
  error: { fontSize: 12.5, color: "var(--crit)", marginTop: 12 } satisfies CSSProperties,
  result: { marginTop: 20 } satisfies CSSProperties,
  warning: {
    fontSize: 12,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    border: "1px solid var(--border)",
    borderRadius: 7,
    padding: "8px 11px",
    marginBottom: 10,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  bodyLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 8,
  } satisfies CSSProperties,
  body: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-elevated)",
    padding: 14,
    fontSize: 13,
    lineHeight: 1.55,
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
  disabledHint: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 12,
    lineHeight: 1.45,
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
} as const;
